fun main() {
    println("Add Method:")
    println("List 1 before the method add:")
    val list = mutableListOf<Int>(1, 3, 5)
    println(list)
    list.add(9)
    println("List 1 after the method add:")
    println(list)
    println("List 1 after append with another manner, list.add(index: 1, element:9):")
    list.add(1, 9)
    println(list)

    println()

    println("Remove Method:")
    println("List 2 before the method remove:")
    val list2 = mutableListOf<Int>(1, 3, 5)
    println(list2)
    list2.remove(3)
    println("List 2 after the method remove:")
    println(list2)
    println("Remove by index:")
    println("List 2 after the method remove by index:")
    list2.removeAt(0)
    println(list2)

    println()

    println("Combine 2 lists:")
    val list3 = mutableListOf<String>()
    println("List 3 before append:")
    println(list3)
    list3.add(0, "J")
    list3.add(1, "O")
    list3.add(2, "S")
    list3.add(3, "E")
    println("List 3 after append:")
    println(list3)

    val list4 = mutableListOf<String>()
    println("List 4 before append:")
    println(list4)
    list4.add(0, "A")
    list4.add(1, "U")
    list4.add(2, "G")
    list4.add(3, "U")
    list4.add(4, "S")
    list4.add(5, "T")
    list4.add(6, "O")
    println("List 4 after append:")
    println(list4)

    println("Combine 2 lists")
    println(list3 + list4)
}